//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomagtachi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tomagtachi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cat {
            get {
                object obj = ResourceManager.GetObject("Cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Name...,Snake,55,55,30,55,55
        ///.
        /// </summary>
        public static string current_pet {
            get {
                return ResourceManager.GetString("current pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dog {
            get {
                object obj = ResourceManager.GetObject("Dog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A|The first letter of the English and of many other alphabets. The capital A of the alphabets of Middle and Western Europe, as also the small letter (a), besides the forms in Italic, black letter, etc., are all descended from the old Latin A, which was borrowed from the Greek Alpha, of the same form; and this was made from the first letter (/) of the Phoenician alphabet, the equivalent of the Hebrew Aleph, and itself from the Egyptian origin. The Aleph was a consonant letter, with a guttural breath sound th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string finalwordsandhints {
            get {
                return ResourceManager.GetString("finalwordsandhints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fish {
            get {
                object obj = ResourceManager.GetObject("Fish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,0,0,0,0
        ///0,0,0,0,0,0
        ///0,0,0,0,0,0
        ///0,0,0,0,0,0
        ///0,0,0,0,0,0
        ///0,0,0,0,0,0
        ///0,0,0,0,0,0
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50,50,50,50
        ///0,50,50 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Past_pets {
            get {
                return ResourceManager.GetString("Past pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Snake {
            get {
                object obj = ResourceManager.GetObject("Snake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E|The fifth letter of the English alphabet
        ///Each|Every sometimes used interchangeably with every
        ///Eachwhere|Everywhere
        ///Eadish|See Eddish
        ///Eager|Sharp sour acid
        ///Eager|Sharp keen bitter severe
        ///Eager|Excited by desire in the pursuit of any object
        ///Eager|Brittle inflexible not ductile
        ///Eager|Same as Eagre
        ///Eagerly|In an eager manner
        ///Eagerness|The state or quality of being eager ardent desire
        ///Eagerness|Tartness sourness
        ///Eagle|Any large, rapacious bird of the Falcon family
        ///Eagless|A female or hen eaglees
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wordsandhints2 {
            get {
                return ResourceManager.GetString("wordsandhints2", resourceCulture);
            }
        }
    }
}
